---
title: "Final Project Code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

a & b.

```{r}
# library statements 
library(readr)
library(ggplot2)
library(dplyr)
library(tidymodels)
tidymodels_prefer()

set.seed(123)

# read in data
Titanic <- read_csv("train.csv")
```

```{r}
# data cleaning
Titanic_clean <- Titanic %>% 
  select(Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked) %>% 
    na.omit()

Titanic_clean
```

```{r}
# creation of cv folds
Titanic_clean_5 <- vfold_cv(Titanic_clean, v = 5)
```

```{r}
# model spec
lm_spec <-
    linear_reg() %>%
    set_engine(engine = "lm") %>% 
    set_mode("regression")

lm_lasso_spec <- 
  linear_reg() %>%
  set_args(mixture = 1, penalty = tune()) %>%
  set_engine(engine = 'glmnet') %>%
  set_mode('regression') 
```

```{r}
# recipes
data_rec <- recipe(Fare ~ ., data = Titanic_clean) %>%
    step_nzv(all_predictors()) %>% 
    step_novel(all_nominal_predictors()) %>% 
    step_normalize(all_numeric_predictors()) %>% 
    step_dummy(all_nominal_predictors())  

# workflows
lm_wf <- workflow() %>%
  add_recipe(data_rec) %>%
  add_model(lm_spec) 

lm_lasso_wf <- workflow() %>% 
  add_recipe(data_rec) %>%
  add_model(lm_lasso_spec)
```

```{r}
# fit & tune models
fit_lm_model <- fit(lm_wf, Titanic_clean)
tidy(fit_lm_model)

fit_lasso_model <- fit(lm_lasso_wf, Titanic_clean)
plot(fit_lasso_model%>% extract_fit_parsnip() %>% pluck('fit'),
     xvar = "lambda") # pick a lambda?
```

c.

```{r}
#  calculate/collect CV metrics
#  For linear regression
lm_result_5 <- fit_resamples(lm_wf,
                             resamples = Titanic_clean_5, 
                             metrics = metric_set(rmse, rsq, mae))

lm_result_5 %>% collect_metrics()

#  for LASSO
penalty_grid <- grid_regular(
  penalty(range = c(-5, 3)),
  levels = 5) # levels = ???

tune_res <- tune_grid(
  lm_lasso_wf, 
  resamples = Titanic_clean_5,
  metrics = metric_set(rmse, mae),
  grid = penalty_grid 
)

autoplot(tune_res) + theme_classic()

best_penalty <- select_best(tune_res, metric = 'rmse')

final_wf <- finalize_workflow(lm_lasso_wf, best_penalty)

final_fit <- fit(final_wf, data = Titanic_clean)

tidy(final_fit)

tune_res %>% collect_metrics() ## ???
```



d.

```{r}
#  visual residuals
lm_model_output <- lm_result_5 %>% 
    predict(new_data = Titanic_clean) %>%
    bind_cols(Titanic_clean) %>%
    mutate(resid = Fare - .pred)

ggplot(fit_lasso_model, aes(x = .pred, y = resid)) +
    geom_point() +
    geom_smooth() +
    geom_hline(yintercept = 0, color = "red") +
    theme_classic()
```

e.


