---
title: "STAT-253_FP_Credit"
author: "STAT 253"
date: "4/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      eval = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(tidymodels)
library(vip)
library(ranger)
library(rpart.plot)
library(broom)
library(kknn)
library(glmnet)
library(ISLR)

tidymodels_prefer()
theme_set(theme_bw())

set.seed(123)

data("Credit")
```

```{r}
# Data Cleaning
Credit <- Credit %>% 
  select(-ID, -Rating)

# Process the data and make the recipe for regression
rec_r <- recipe(Limit ~ ., data = Credit) %>%
  step_nzv(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_corr(all_numeric_predictors())

Credit_cv5 <- vfold_cv(Credit, v = 5)
```

### OLS

```{r}
# model spec for OLS
lm_spec <-
  linear_reg() %>%
  set_engine(engine = "lm") %>%
  set_mode("regression")

# workflow for OLS
lm_wf <- workflow() %>%
  add_recipe(rec_r) %>%
  add_model(lm_spec) 
```

```{r}
# Fit the OLS model
lm_fit <- fit(lm_wf, Credit)
```

```{r}
# Present the OLS model result and its metrics
tidy(lm_fit)
glance(lm_fit)
```

```{r}
#  Calculate and collect CV metrics for OLS
lm_output <- fit_resamples(lm_wf,
                           resamples = Credit_cv5,
                           metrics = metric_set(rmse, rsq, mae))

collect_metrics(lm_output)
```

```{r}
# Visualize the residual plot for OLS
lm_output2 <- lm_fit %>%
  predict(new_data = Credit) %>%
  bind_cols(Credit) %>%
  mutate(resid = Limit - .pred)

ggplot(lm_output2, aes(x = .pred, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()
```

### LASSO

```{r}
# model spec for LASSO
lasso_spec <-
  linear_reg() %>%
  set_args(mixture = 1, penalty = tune()) %>%
  set_engine(engine = 'glmnet') %>%
  set_mode('regression') 

# workflows for LASSO
lasso_wf <- workflow() %>%
  add_recipe(rec_r) %>%
  add_model(lasso_spec)
```

```{r}
# Fit the LASSO model
lasso_fit <- lasso_wf %>%
  fit(data = Credit)
```

```{r}
# Tune the LASSO model
glmnet_output <-
  lasso_fit %>% extract_fit_parsnip() %>% pluck('fit')

lambdas <- glmnet_output$lambda

coefs_lambdas <-
  coefficients(glmnet_output, s = lambdas)  %>%
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  mutate(lambda = lambdas) %>%
  select(lambda, everything(),-`(Intercept)`) %>%
  pivot_longer(cols = -lambda,
               names_to = "term",
               values_to = "coef") %>%
  mutate(var = map_chr(stringr::str_split(term, "_"),  ~ .[1]))

coefs_lambdas %>%
  ggplot(aes(
    x = lambda,
    y = coef,
    group = term,
    color = var
  )) +
  geom_line() +
  theme_classic() +
  theme(legend.position = "bottom", legend.text = element_text(size = 8))
```

```{r}
# Visualize the best penalty term
penalty_grid <- grid_regular(penalty(range = c(-3, 3)),
                             levels = 20)

lasso_cv <- tune_grid(
  lasso_wf,
  resamples = Credit_cv5,
  metrics = metric_set(rmse, mae, rsq),
  grid = penalty_grid
)

autoplot(lasso_cv) + theme_classic()
```

```{r}
# Present the LASSO model result
best_penalty <- select_best(lasso_cv, metric = 'rmse')
lasso_wf2 <- finalize_workflow(lasso_wf, best_penalty)
lasso_fit <- fit(lasso_wf2, data = Credit)
tidy(lasso_fit)
```

```{r}
#  Calculate and collect CV metrics for LASSO
lasso_output <- lasso_cv %>% collect_metrics(summarize = TRUE) %>%
  na.omit() %>% 
  group_by(.metric) %>% 
  summarize(mean = mean(mean))
lasso_output
```

```{r}
# Visualize the residual plot for LASSO
lasso_output2 <- lasso_fit %>%
  predict(new_data = Credit) %>%
  bind_cols(Credit) %>%
  mutate(resid = Limit - .pred)

ggplot(lasso_output2, aes(x = .pred, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()
```

```{r}
# GAM model using mgcv
gam_spec <-
  gen_additive_mod() %>%
  set_engine(engine = 'mgcv') %>%
  set_mode('regression')

gam_mod <- fit(gam_spec,
               Limit ~ s(Income) + Cards + Age + Education + Gender + Student + Married + Ethnicity + s(Balance),
               data = Credit)
```

```{r}
# Present the GAM model result
gam_mod %>% pluck('fit') %>% summary() 
```

```{r}
# Visualize the evaluation plots for GAMs
par(mfrow = c(2, 3))
gam_mod %>% pluck('fit') %>% mgcv::gam.check()
gam_mod %>% pluck('fit') %>% plot()
```

```{r}
# Visualize the residual plot for GAMs
gam_output <- Credit %>%
  bind_cols(predict(gam_mod, new_data = Credit)) %>%
  mutate(resid = Limit - .pred)

ggplot(gam_output, aes(x = Income, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()

ggplot(gam_output, aes(x = Education, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()

ggplot(gam_output, aes(x = Balance, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()

ggplot(gam_output, aes(x = .pred, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  theme_classic()
```

```{r}
#  Calculate and collect CV metrics for GAMs
gam_spec2 <-
  linear_reg() %>%
  set_engine(engine = 'lm') %>%
  set_mode('regression')

gam_rec <- rec_r %>%
  step_naomit(all_numeric_predictors(), skip = FALSE) %>%
  step_ns(Income, deg_free = 1.481) %>% 
  step_ns(Balance, deg_free = 8.426)

gam_wf <- workflow() %>%
  add_model(gam_spec2) %>%
  add_recipe(gam_rec)

gam_output <- fit_resamples(gam_wf,
                            resamples = Credit_cv5,
                            metrics = metric_set(mae, rmse, rsq))

gam_output %>% collect_metrics()
```

### Evaluation (OLS, LASSO, GAMs)

```{r}
regreDF <- lm_output %>%
  collect_metrics() %>% 
  mutate(OLS = mean) %>% 
  select(.metric, OLS) %>% 
  left_join(lasso_output %>% 
              mutate(LASSO = mean) %>% 
              select(.metric, LASSO), 
            by = ".metric") %>% 
  left_join(gam_output %>% 
              collect_metrics() %>% 
              mutate(GAMs = mean) %>% 
              select(.metric, GAMs), 
            by = ".metric")

regreDF
```











